# see: https://gist.github.com/daicham/5ac8461b8b49385244aa0977638c3420
image: java:11-jdk

stages:
  #- build
  - test
  #- deploy

#before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
#  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  script:
    - ./gradlew check

#deploy:
#  stage: deploy
#  script:
#    - ./deploy

after_script:
  - echo "End CI"
